Server improvements from pr 4
jonas27/ramp-up-go pull request #15
Opened 2023-07-10 14:19 UTC by jonas27

2023-07-12 10:56 UTC, avorima requested changes

2023-07-12 10:56 UTC, avorima commented on server/main.go
> +		port = flags.String("port", ":8080", "The server port with colon")
address

2023-07-12 10:56 UTC, avorima commented on server/server_test.go
> +		{name: "key does not exist", code: http.StatusNotFound, path: "/", key: "test1"},
The test succeeds if you use the correct key. Seems like the routes aren't set up correctly

2023-07-12 10:56 UTC, avorima commented on server/server_test.go
> +		response string
unused

2023-07-12 10:56 UTC, avorima commented on server/server_test.go
> +		response string
unused

2023-07-13 12:56 UTC, jonas27 commented on server/main.go
> +		port = flags.String("port", ":8080", "The server port with colon")
yeah, I fixed it in the old PR and now I am stuck merging it up with every PR (included in new PR)

2023-08-02 11:30 UTC, closed without merging