Put and query params
jonas27/ramp-up-go pull request #4
Opened 2023-07-05 08:12 UTC by jonas27

2023-07-10 09:53 UTC, Ntr0 requested changes

2023-07-10 09:53 UTC, Ntr0 commented on server/db.go
> +	if !db.keyExists(key) {
this looks like you're reimplementing map value retrieval.

2023-07-10 09:53 UTC, Ntr0 commented on server/server.go
> +	_, ok := s.db.get(key)
keyExists would be semantically better :)

2023-07-10 09:53 UTC, Ntr0 commented on server/server.go
> +// according to rfc guidlines PUT should create or replace resources
typo, guidelines

2023-07-10 09:53 UTC, Ntr0 commented on server/server.go
> +		w.WriteHeader(http.StatusCreated)
You are answering before fulfilling the request

2023-07-10 09:53 UTC, Ntr0 commented on server/server_test.go
> +// TODO: for all tests: split path to path + key vars for better  testing
Do the TODO :)

2023-07-10 09:53 UTC, Ntr0 commented on server/server_test.go
> +func TestPut(t *testing.T) {
75% failure. Please fix

2023-07-10 09:53 UTC, Ntr0 commented on server/server_test.go
> +		{name: "works, weird body", path: "/?key=test", reqBody: "ntest!@#$%^&*({ }+=)-/\\/test_;'\"", code: http.StatusOK, response: "succeeded"},
Weird? That's not even utf-8 :question::exclamation:

2023-07-10 14:21 UTC, jonas27 commented
@Ntr0  to avoid too many merge conflicts fixes are here https://github.com/jonas27/ramp-up-go/pull/15

2023-07-12 09:21 UTC, jonas27 commented
> @Ntr0 to avoid too many merge conflicts fixes are here #15

@Ntr0 @avorima please have a look again :) (PR for fixes is #15 )

2023-07-12 10:26 UTC, jonas27 commented
> > @Ntr0 to avoid too many merge conflicts fixes are here #15
> 
> @Ntr0 @avorima please have a look again :) (PR for fixes is #15 )

I merge ;)

2023-07-12 10:27 UTC, merged